import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildHarnessFiles, harnessReport } from '../soul-builder.mjs';
import { populationFile, upsertSoul, registerSoulDir } from '../agent-population.mjs';
import { buildSoulDirectory } from '../soul-build.mjs';
import { computePackageRevision, readSoulPackageEntries, GENERATED_HARNESS_MARKER as MARKER, GENERATED_HARNESS_PATHS, PACKAGE_IGNORE_LIST } from '../soul-package.mjs';
const cli = fileURLToPath(new URL('../agent-bot.mjs', import.meta.url));
const vectors = JSON.parse(readFileSync(new URL('./fixtures/soul-package/vectors.json', import.meta.url)));
function fixture(t) {
  const root = mkdtempSync(join(tmpdir(), 'soul-builder-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  for (const entry of vectors[0].entries) {
    const path = join(root, entry.path);
    mkdirSync(dirname(path), { recursive: true });
    if (entry.mode === '040000') mkdirSync(path);
    else writeFileSync(path, Buffer.from(entry.base64, 'base64'));
  }
  const manifest = JSON.parse(readFileSync(join(root, 'soul.json')));
  writeFileSync(join(root, 'soul.json'), JSON.stringify({ ...manifest, formatVersion: 2, ignore: PACKAGE_IGNORE_LIST }));
  return root;
}
function put(root, path, bytes) { mkdirSync(dirname(join(root, path)), { recursive: true }); writeFileSync(join(root, path), bytes); }

test('pure output is sorted, deterministic, input-independent and confined to the v2 paths', (t) => {
  const root = fixture(t);
  const { entries } = readSoulPackageEntries(root);
  const before = entries.map((e) => [e.path, e.mode, e.bytes.toString('base64')]);
  const a = buildHarnessFiles(entries), b = buildHarnessFiles([...entries].reverse());
  assert.deepEqual(a, b);
  assert.deepEqual([...a.keys()], [...a.keys()].sort());
  assert.deepEqual(entries.map((e) => [e.path, e.mode, e.bytes.toString('base64')]), before);
  for (const [path, bytes] of a) {
    assert.ok(GENERATED_HARNESS_PATHS.some((p) => p.endsWith('/') ? path.startsWith(p) : p === path));
    assert.equal(bytes.includes(13), false);
  }
  assert.equal(a.get('CLAUDE.md').toString(), `${MARKER}\n@AGENTS.md\n`);
  assert.equal(a.get('GEMINI.md').toString(), `${MARKER}\n@AGENTS.md\n`);
  // Codex now receives `.codex/config.toml` for its MCP entry (#378) and
  // OpenCode its `opencode.json`; neither gets a duplicate skills folder.
  assert.ok(a.has('.codex/config.toml') && a.has('opencode.json'));
  // Cursor and Kiro receive only their MCP file; no harness duplicates the skills.
  assert.ok(a.has('.cursor/mcp.json') && a.has('.kiro/settings/mcp.json'));
  assert.ok([...a.keys()].every((p) => !/^\.(cursor|opencode|devin|kiro)\//.test(p) || ['.cursor/mcp.json', '.kiro/settings/mcp.json'].includes(p)),
    'compatible harnesses receive no duplicate folder');
  assert.throws(() => buildHarnessFiles([{ path: 'skills/../escape', bytes: Buffer.alloc(0) }]), /unsafe/);
});

test('build and rebuild preserve v2 revision; edits to generated bytes participate', (t) => {
  const root = fixture(t), revision = computePackageRevision(root);
  assert.ok(buildSoulDirectory(root, { check: true }).drift.includes('CLAUDE.md'));
  assert.equal(existsSync(join(root, 'CLAUDE.md')), false);
  buildSoulDirectory(root);
  assert.equal(computePackageRevision(root), revision);
  assert.deepEqual(buildSoulDirectory(root, { check: true }).drift, []);
  buildSoulDirectory(root);
  assert.equal(computePackageRevision(root), revision);
  put(root, 'CLAUDE.md', `${MARKER}\nhand edited\n`);
  assert.notEqual(computePackageRevision(root), revision);
  assert.ok(buildSoulDirectory(root, { check: true }).drift.includes('CLAUDE.md'));
  assert.match(readFileSync(join(root, 'CLAUDE.md'), 'utf8'), /hand edited/);
  buildSoulDirectory(root);
  assert.equal(computePackageRevision(root), revision);
});

test('unmarked conflicts are reported before any write or stale deletion', (t) => {
  const root = fixture(t);
  put(root, 'CLAUDE.md', `authored\nA quoted marker: ${MARKER}\n`);
  put(root, '.claude/stale.md', `${MARKER}\nold\n`);
  for (const check of [true, false]) assert.throws(() => buildSoulDirectory(root, { check }), /unmarked.*CLAUDE.md/);
  assert.match(readFileSync(join(root, 'CLAUDE.md'), 'utf8'), /^authored/);
  assert.equal(existsSync(join(root, 'GEMINI.md')), false);
  assert.equal(existsSync(join(root, '.claude/stale.md')), true);
});

test('stale marked files and empty containers are removed, authored files survive', (t) => {
  const root = fixture(t);
  buildSoulDirectory(root);
  const revision = computePackageRevision(root);
  put(root, '.claude/old/deep/stale.md', `${MARKER}\nold\n`);
  put(root, '.cursor/authored.md', 'authored');
  assert.deepEqual(buildSoulDirectory(root, { check: true }).removals, ['.claude/old/deep/stale.md']);
  assert.equal(existsSync(join(root, '.claude/old/deep/stale.md')), true);
  buildSoulDirectory(root);
  assert.equal(existsSync(join(root, '.claude/old')), false);
  assert.equal(readFileSync(join(root, '.cursor/authored.md'), 'utf8'), 'authored');
  rmSync(join(root, '.cursor'), { recursive: true });
  assert.equal(computePackageRevision(root), revision);
});

test('skills retain front matter first, copy text/scripts, preserve executable mode and point at opaque assets', (t) => {
  const root = fixture(t);
  put(root, 'skills/hello/SKILL.md', '---\r\nname: hello\r\ndescription: Say hello\r\n---\r\nHello\r\n');
  put(root, 'skills/hello/references/help.md', 'Help\r\n');
  put(root, 'skills/hello/scripts/run.sh', '#!/bin/sh\r\necho hello\r\n');
  chmodSync(join(root, 'skills/hello/scripts/run.sh'), 0o755);
  put(root, 'skills/hello/assets/blob.bin', Buffer.from([0, 255]));
  put(root, 'skills/hello/config.json', '{"key": 1}');
  const revision = computePackageRevision(root);
  buildSoulDirectory(root);
  const skill = readFileSync(join(root, '.claude/skills/hello/SKILL.md'), 'utf8');
  assert.ok(skill.startsWith(`---\nname: hello\ndescription: Say hello\n---\n${MARKER}\nHello\n`));
  assert.equal(readFileSync(join(root, '.gemini/skills/hello/SKILL.md'), 'utf8'), skill);
  assert.match(skill, /\.\.\/\.\.\/\.\.\/skills\/hello\/assets\/blob.bin/);
  assert.equal(readFileSync(join(root, '.claude/skills/hello/references/help.md'), 'utf8'), `${MARKER}\nHelp\n`);
  assert.equal(readFileSync(join(root, '.claude/skills/hello/scripts/run.sh'), 'utf8'), `#!/bin/sh\n# ${MARKER}\necho hello\n`);
  assert.equal(statSync(join(root, '.claude/skills/hello/scripts/run.sh')).mode & 0o111, 0o111);
  assert.equal(existsSync(join(root, '.claude/skills/hello/config.json')), false);
  assert.equal(computePackageRevision(root), revision);
  rmSync(join(root, 'skills/hello'), { recursive: true });
  buildSoulDirectory(root);
  assert.equal(existsSync(join(root, '.claude/skills/hello')), false);
});

test('a disabled skill renders nothing for any harness while its source directory and the other skills stay', (t) => {
  const root = fixture(t);
  put(root, 'skills/hello/SKILL.md', '---\nname: hello\ndescription: Say hello\n---\nHello\n');
  put(root, 'skills/hello/references/help.md', 'Help\n');
  put(root, 'skills/hello/scripts/run.sh', '#!/bin/sh\necho hello\n');
  put(root, 'skills/other/SKILL.md', '---\nname: other\ndescription: Other\n---\nOther\n');
  const manifest = JSON.parse(readFileSync(join(root, 'soul.json')));
  const declare = (disabled) => writeFileSync(join(root, 'soul.json'), JSON.stringify({ ...manifest, skills: { disabled } }));
  buildSoulDirectory(root);
  assert.ok(existsSync(join(root, '.claude/skills/hello/SKILL.md')) && existsSync(join(root, '.gemini/skills/hello/SKILL.md')));
  declare(['hello']);
  const { entries } = readSoulPackageEntries(root);
  const output = buildHarnessFiles(entries);
  assert.deepEqual([...output.keys()].filter((path) => /skills\//.test(path)), ['.claude/skills/other/SKILL.md', '.gemini/skills/other/SKILL.md']);
  assert.equal(harnessReport(output).claude.rendered.includes('skills'), true);
  const sourcePaths = entries.map((entry) => entry.path);
  for (const path of ['skills/hello/SKILL.md', 'skills/hello/references/help.md', 'skills/hello/scripts/run.sh']) assert.ok(sourcePaths.includes(path), path);
  // A rebuild removes the stale copies and leaves `skills/hello/` alone.
  buildSoulDirectory(root);
  for (const path of ['.claude/skills/hello', '.gemini/skills/hello']) assert.equal(existsSync(join(root, path)), false, path);
  assert.ok(existsSync(join(root, '.claude/skills/other/SKILL.md')) && existsSync(join(root, '.gemini/skills/other/SKILL.md')));
  assert.equal(readFileSync(join(root, 'skills/hello/references/help.md'), 'utf8'), 'Help\n');
  const revision = computePackageRevision(root);
  // A name no directory matches is fine; the profile reports it.
  declare(['hello', 'later']);
  buildSoulDirectory(root);
  assert.ok(existsSync(join(root, '.claude/skills/other/SKILL.md')));
  // With every skill off there is no skills directory and no `skills` in the report.
  declare(['hello', 'other']);
  const report = buildSoulDirectory(root);
  for (const path of ['.claude/skills', '.gemini/skills']) assert.equal(existsSync(join(root, path)), false, path);
  for (const harness of Object.values(report.harnesses)) assert.equal(harness.rendered.includes('skills'), false);
  assert.ok(report.harnesses.claude.rendered.includes('instructions'));
  assert.ok(existsSync(join(root, 'skills/hello/SKILL.md')) && existsSync(join(root, 'skills/other/SKILL.md')));
  // Switching back on restores the copies byte for byte.
  declare([]);
  buildSoulDirectory(root);
  const skill = readFileSync(join(root, '.claude/skills/hello/SKILL.md'), 'utf8');
  assert.ok(skill.startsWith(`---\nname: hello\ndescription: Say hello\n---\n${MARKER}\nHello\n`));
  assert.equal(readFileSync(join(root, '.gemini/skills/hello/SKILL.md'), 'utf8'), skill);
  assert.equal(readFileSync(join(root, '.claude/skills/hello/references/help.md'), 'utf8'), `${MARKER}\nHelp\n`);
  // Off again lands on the same revision: the switch is only the declaration.
  declare(['hello']);
  buildSoulDirectory(root);
  assert.equal(computePackageRevision(root), revision);
});

for (const target of ['CLAUDE.md', '.claude', '.claude/skills', '.claude/skills/hello']) {
  test(`rejects symlinks at ${target} without touching their destination`, (t) => {
    const root = fixture(t), outside = mkdtempSync(join(tmpdir(), 'soul-outside-'));
    t.after(() => rmSync(outside, { recursive: true, force: true }));
    mkdirSync(dirname(join(root, target)), { recursive: true });
    symlinkSync(outside, join(root, target));
    assert.throws(() => buildSoulDirectory(root), /conflict/);
    assert.equal(existsSync(join(root, 'GEMINI.md')), false);
  });
}

test('CLI dispatch supports build/check and returns nonzero for drift/conflicts/syntax', (t) => {
  const root = fixture(t);
  const run = (...args) => spawnSync(process.execPath, [cli, 'soul', 'build', ...args], { encoding: 'utf8', env: { PATH: process.env.PATH, HOME: root } });
  assert.equal(run(root, '--check').status, 1);
  assert.equal(run(root).status, 0);
  assert.equal(run('--check', root).status, 0);
  put(root, 'CLAUDE.md', 'authored');
  assert.match(run(root).stderr, /conflict/);
  for (const args of [[root, 'extra'], ['--bad'], ['--check', '--check'], []]) assert.equal(run(...args).status, 1);
});


test('default CLI path uses the current soul registered directory, not cwd', (t) => {
  const root = fixture(t);
  const id = 'agent_33333333-3333-4333-8333-333333333333';
  const options = { env: {}, home: root, config: {} };
  const file = populationFile(options);
  upsertSoul({ id, status: 'active', spacePath: join(root, 'space') }, { file });
  put(root, '.soul-state/agent-id', `${id}\n`);
  registerSoulDir(id, root, { file });
  const result = spawnSync(process.execPath, [cli, 'soul', 'build'], {
    cwd: tmpdir(), encoding: 'utf8', env: { PATH: process.env.PATH, HOME: root, AGENT_BOT_ID: id },
  });
  assert.equal(result.status, 0, result.stderr);
  assert.equal(readFileSync(join(root, 'CLAUDE.md'), 'utf8'), `${MARKER}\n@AGENTS.md\n`);
});
